version: '3.4'

services:
  
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: jusi
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    
    
  jusilms:
    image: ${DOCKER_REGISTRY-}jusilms
    restart: always
    build:
      context: .
      dockerfile: JusiLms/Dockerfile
    ports:
        - 80:80
        - 443:443
        - 80:12345
    environment:
        DOCKER_POSTGRESS_CONNECTION_STRING: User ID=postgres;Password=example;Host=postgres;Port=5432;Database=jusi;
        JUSI_API_HOST: jusilms:80
        RUNNING_IN_DOCKER: true
    volumes:
      - ./wwwroot/avatars:/app/wwwroot/avatars
    depends_on: 
      - postgres
